# Generated by Django 5.1.2 on 2024-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(default=False, max_length=250, verbose_name='Descripción de imagen'),
        ),
    ]
