# Generated by Django 5.1.2 on 2024-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción de imagen'),
        ),
    ]
